### ISSUE TITLE
Extract direction/heading of the location out of EXIF/metadata

### ISSUE THREAD

**Issue by raymondde** [robinkrahl/LrMediaWiki#35]
Extract direction/heading of the location out of EXIF/metadata and add it to the location template

**Comment by robinkrahl** [comment]
[Access to the `gpsImgDirection` field](http://lightroomsolutions.com/sdk/modules/LrPhoto.html#photo:getRawMetadata) was added in version 6.0 of the Lightroom SDK.

**Comment by Hasenlaeufer** [comment]
I will have a try to fix this. Please don't blame me for my first try to deal with this project, Lightroom SDK, Lua and GitHub.
My actual concerns are:
* Which dependencies exist between Lightroom versions and SDK versions? What happens to users of this plugin with older Lightroom versions, if a feature of version 6.0 of the Lightroom SDK is used?
* According GitHub: Is it better to create a branch here or at GitHub Desktop? I assume, a branch should be initiated here, so I will do so. This shouldn't be a problem, right?

**Comment by robinkrahl** [comment]
@Hasenlaeufer 

Great! :-)

 - At the moment, LrMediaWiki should work with Lightroom 5 and higher. I do not know about previous versions.  For this change, there are two options:
    - As far as I know, `LrPhoto:getRawMetadata` returns `nil`  if the key is invalid, so we can just check its return value.
    - If I’m wrong and `LrPhoto:getRawMetadata` fails if the key is invalid, we could add an option to the settings dialog to enable/disable GPS heading information in the Location template.
 - I’m not familiar with the GitHub Desktop application.  But everything you need to do also works in the web application, so it should be fine to do it here.  I’d suggest that you create your own fork of the project.  (The ‘fork’ button should be on the right top of this page.)  Then you can directly commit to your own repository, and once you are done, we can merge your commits into the main repository.

**Comment by robinkrahl** [comment]
(The relevant code snippet is [here](https://github.com/robinkrahl/LrMediaWiki/blob/master/mediawiki.lrdevplugin/MediaWikiExportServiceProvider.lua#L107), in `MediaWikiExportServiceProvider`, function `processRenderedPhotos`.)

**Comment by Hasenlaeufer** [comment]
Robin, according to your proposals:

*As far as I know, LrPhoto:getRawMetadata returns nil if the key is invalid, so we can just check its return value.*
* This is not a good idea. With LR 5 the call of LrPhoto:getRawMetadata() with the parameter "gpsImgDirection" leads to a warning message: Warning – Unable to Export: An internal error has occurred: Unknown key: "gpsImgDirection"<br />
(BTW, even it's a warning, the export is cancelled.)<br />
To avoid this warning message, a prior version check is needed.

*... if the key is invalid, we could add an option to the settings dialog to enable/disable GPS heading information in the Location template.*

* I took another approach. The user will see a hint message, wether the setting of "heading" works or works not, dependant from the LR version in use. In addition, the user gets informed, why the setting works or works not. The message box includes a "Don't show again" checkbox. At LR versions >= 6, this hint box appears only, if the LR "direction" field is set.

**Comment by Hasenlaeufer** [comment]
I took this item as an opportunity to step into the development of the plugin. @robinkrahl welcomes this, and I thank him for supporting me to get familiar with the development environment. [Here] (https://github.com/Hasenlaeufer/LrMediaWiki/blob/master/CHANGELOG.md#v042) I describe the current state of affairs.
