### ISSUE TITLE
Upload Error: Warning

### ISSUE THREAD

**Issue by ubahnverleih** [robinkrahl/LrMediaWiki#42]
Other uploads has worked. I've no idea why this upload fails.
Lightroom CC, Mac OSX 10.9.5 
![bildschirmfoto 2015-05-16 um 15 51 28](https://cloud.githubusercontent.com/assets/371280/7666392/f1e0aaa8-fbe3-11e4-9924-6a3ec045f951.png)

**Comment by robinkrahl** [comment]
I am sorry for the poor error message; that’s something I’m working on. – The same error is caused if there are two or more consecutive white spaces or underlines in the file name (see #37). Does this apply to this upload?

**Comment by ubahnverleih** [comment]
Oh right - that helps. Thank you.
