### ISSUE TITLE
Support for Jeffrey’s “Metadata-Viewer Preset Editor” 

### ISSUE THREAD

**Issue by toresetre** [robinkrahl/LrMediaWiki#48]
“Metadata-Viewer Preset Editor”  incorporates the ability to include the custom metadata from other Lightroom plugins in your presets. According to the plugin author, "if you would like your plugin's custom metadata available to the user here, send a note to jfriedl@yahoo.com with the plugin name, web site, plugin id and your plugin's LrMedataProfider file". 
Source: http://regex.info/blog/lightroom-goodies/metadata-presets

**Comment by Hasenlaeufer** [comment]
The mentioned phrase I couldn't find at the source.
Does this mean, the plugin author retired his offer?

**Comment by toresetre** [comment]
I can no longer find that phrase either. I guess it means that the offer to include other plugins is not longer available unfortunately.

**Comment by toresetre** [comment]
I've found the offer from the author. It's actually in the plugin, not on the website. So the offer is still there. Since LrMediaWiki 0.5 includes many more fields than before, this request is even more relevant.

![screenshot](https://cloud.githubusercontent.com/assets/16445816/20867377/26303444-ba43-11e6-84b8-c2ae20141d9d.jpg)

**Comment by Hasenlaeufer** [comment]
Thanks to the hint!
I will check Jeffrey’s plugin and look what can be done.

**Comment by Hasenlaeufer** [comment]
Dear toresetre,
today I took the time to install Jeffrey’s plugin to see how it works. Sorry for being late!
Using the button "import fields from plugin" and navigating to the installation folder of LrMediaWiki resulted to have the custom fields of LrMediaWiki available – see the screenshot below.
Therefore I don't understand, why it should be needed to ask Jeffrey to support LrMediaWiki.
It seems, I missed something. Do you have an idea what might be the difference to let Jeffrey support LrMediaWiki or not?
Up to now the only difference I can see, is to avoid the steps to select the LrMediaWiki plugin I described above. Would this make a significant difference?
![screenshot](https://cloud.githubusercontent.com/assets/16976532/21574011/f6547c04-ceeb-11e6-82a7-a0ad9445a5ba.jpg)

**Comment by toresetre** [comment]
Dear Hasenlaeufer,
This is acutually what I have been trying to do with the plugin. I couldb't get it to do this previously (I only tried to open files, not the whole directory), but I've now been able to complete what I wanted to do.
This concludes my request and I suggest that it will be closed.
Thanks
Tore
