### ISSUE TITLE
Leading space in title fields results in a Lua error

### ISSUE THREAD

**Issue by raymondde** [robinkrahl/LrMediaWiki#49]
A leading space in title fields results in a Lua error during export: 

![lrplugin lua error](https://cloud.githubusercontent.com/assets/4243486/12239463/2cdf6e7a-b889-11e5-807b-0160e8b3f39f.png)

**Comment by robinkrahl** [comment]
Thanks for reporting! Should be fixed now. Do you think I should a bug-fix release for this fix?

**Comment by raymondde** [comment]
A very uncommon type error I think. First time for me. IMO not worth for a bug fix release.
