### ISSUE TITLE
Support of LR 4

### ISSUE THREAD

**Issue by Hasenlaeufer** [robinkrahl/LrMediaWiki#50]
If I try to install LrMediaWiki at Lightroom 4, at "Lightroom Plugin-Manager" the plug-in is marked by a red dot, it's mentioned as "mediawiki" (instead of "MediaWiki for Lightroom") and the subtitle is "Installed but not working". Can this be fixed with low effort? Maybe, there are users still working with LR 4.

**Comment by Hasenlaeufer** [comment]
This has been fixed with v0.4.2.

**Comment by robinkrahl** [comment]
Thanks, fixed with fe78c8f.
