### ISSUE TITLE
Make LrMediaWiki compatible with BotPasswords

### ISSUE THREAD

**Issue by raymondde** [robinkrahl/LrMediaWiki#61]
Since activation of the Two-Factor Authentication yesterday BotPasswords, created via [[Special:BotPasswords]] are necessary for uploading via LrMediaWiki. I created one for my account but was not able to upload with the bot credentials. 

Neither in the form "Username@Botname" + Password nor with "Username" + "Botname@Password" as suggested by the BotPassword form.

Error message: "Login fehlgeschlagen: Aborted"

**Comment by raymondde** [comment]
Strike this. my fault

**Comment by Hasenlaeufer** [comment]
This issue is related to #65: "Warnings: Deprecated MediaWiki API calls (login, token) (enhancement)" and #67: "Login: Support both, main-accounts and bot-accounts (enhancement)".
