### ISSUE TITLE
Error when upgrading to 0.5.1

### ISSUE THREAD

**Issue by toresetre** [robinkrahl/LrMediaWiki#70]
I've upgraded from 0.5.0 to 0.5.1. The first time I load the plugin I get an error message "An internal error has occured: Searchable strings must be less than 512 bytes; this value is 606 bytes". The plugin then will not load. 
This is an bug.
![image](https://cloud.githubusercontent.com/assets/16445816/21822435/6c02ff50-d777-11e6-9be7-42fc38ae5e65.png)

**Comment by Hasenlaeufer** [comment]
I was afraid, that this might happen. Related discussions are at [Adobe SDK forum](https://forums.adobe.com/thread/2255286) and [Wikimedia Commons](https://commons.wikimedia.org/wiki/Commons_talk:LrMediaWiki#Searchable). Unfortunately, the discussion at Adobe SDK forum did not lead to a satisfying solution.
The only "bulletproof" solution is, to withdraw the feature "Enable search of metadata fields", see #66.
I don't have any better idea. Obviously, my assumptions failed, which fields might exceed (or might not) the limit of 511 bytes.
I'll prepare a version 0.5.2, withdrawing the mentioned feature.

**Comment by Hasenlaeufer** [comment]
I published a version 0.5.2 which should solve this bug.
Tore, please give me a feedback if this version works at your use case.

**Comment by toresetre** [comment]
I can confirm that 0.5.2 does not have this error. This version seems to work fine.

**Comment by Hasenlaeufer** [comment]
Tore, thanks for your feedback! Unfortunately I forgot to update the version number. Please use 0.5.3 – the only difference is an updated version number. Feel free to close this issue – I don't have the permission to do it.

**Comment by toresetre** [comment]
Thanks, it's working fine now with the 0.5.3 version.
