### ISSUE TITLE
Additional variables

### ISSUE THREAD

**Issue by toresetre** [robinkrahl/LrMediaWiki#74]
Re. the latest version (0.6.0). The concept of using Lightroom variables are interesting. I'll try to work these into my workflow.

While I explore the possibilities this functionality have, here are some suggestions for additional Lightroom variables that can be usefull (Today I'm putting these variables in manually in filename, caption and/or categories):

- Photo creation date (Full date, Month and Year)
- Camera model
- Lens
- Job identifier
- Event
- Person Shown in the photo
- Name of Organization
- Sublocation
- City
- State / Province
- Country

**Comment by Hasenlaeufer** [comment]
Implemented and published by release 0.7.

**Comment by Hasenlaeufer** [comment]
To avoid/minimize discussions, which fields are to be provided or not, all Exif and IPTC Core fields are provided. The fields of the "IPTC extension" are partly covered.

**Comment by toresetre** [comment]
Great! I've tested this and it looks very good.

I'd like to add that there's some benefit if the photo cration date can be customized. The use case would be to add categories like "Photographs taken on 2017-02-26" and "February 2017 in Norway". I add categories like this manually today. Both would require various formating of the Photo creation date placeholder.

**Comment by Hasenlaeufer** [comment]
Your examples can be covered by setting categories to

- {{Taken on|&lt;creationDate>}}
- {{ISOmonth|&lt;creationDate>}} {{ISOyear|&lt;creationDate>}} in Norway

"ISOmonth" works only if the user has set English as language. It returns a localized month name, e.g. "February" in English, "Februar" in German. This is a problem.
I have to think about a solution. Maybe, an additional placeholder &lt;creationMonthName> returning the month name in English would solve it.
Maybe, further placeholders like &lt;creationYear>, &lt;creationMonth> and &lt;creationDay> (returning numbers) make sense?

BTW, I implemented an additional "Date" field to let the user customize the date – see issue "Date field #83". This will be part of the next release.

**Comment by toresetre** [comment]
Thanks for the tip on using ISOmonth etc for this. I'll try it out on my next upload to Commons.

<creationYear>, <creationMonth> and <creationDay> makes good sense and it would be helpful. I see the issue with localized month names, but if you add a placeholder <creationMonthName> that would solve this I suspect.

**Comment by Hasenlaeufer** [comment]
I opened a new issue: "Additional placeholders related to creation date #91"

**Comment by Hasenlaeufer** [comment]
Proposal: Close this issue.
