### ISSUE TITLE
Additional metadata sets

### ISSUE THREAD

**Issue by Hasenlaeufer** [robinkrahl/LrMediaWiki#80]
Currently, the plug-in provides one metadata set: "MediaWiki for Lightroom". It includes all fields of all supported infobox templates, starting with a general section (used by all infobox templates) and providing groups for "Artwork" and "Object photo".

We should introduce additional metadata sets, related to the infobox templates. Then we would have these metadata sets:

- LrMediaWiki – All Fields (formerly: "MediaWiki for Lightroom")
- LrMediaWiki – Artwork
- LrMediaWiki – Information
- LrMediaWiki – Object Photo

The new metadata sets should only show the fields of the related infobox templates.

**Comment by raymondde** [comment]
Sounds like a good idea.

**Comment by Hasenlaeufer** [comment]
An extension of the proposal. The additional metadata sets could provide two sections:
* At the first section with title "LrMediaWiki", the fields of the related infobox templates should be shown.
* At the second section with title "Lightroom", a selection of Lightroom-built-in fields should be shown.

The idea of the second section is, to minimize user's efforts by changing between different metadata sets to view/edit Lightroom fields. These fields should be provided at the second section:
* File Name
* Copy Name
* Headline
* Title
* Caption
* Date Created
* Capture Time – this field provides access to dialog "Edit Capture Time", see metadata set "Default"
* Capture Date
* Sublocation
* City
* State / Province
* Country
* Job Identifier
* Person Shown
* Name of Org Shown
* Event

**Comment by Hasenlaeufer** [comment]
Provided by pre-release 0.8.
